import { Fragment, type ReactNode } from "react";

import { CoinIcon } from "@/components/ui/CoinAmount";

/**
 * Notification bodies generated by SQL triggers (bet_placed body
 * `"You bet 5.00 on \"X\""`), SQL functions (welcome, top_up), and
 * the notify-payout edge function ("27.00 credited from ...") carry
 * money values formatted as either `$X` or bare `X.XX`. Replace
 * every match with a coin glyph + bare digit span.
 *
 * Regex matches:
 *   `$<number>` — strips the dollar sign, replaces with coin glyph
 *   `<number>.<dd>` (bare) — requires two-digit decimal + word
 *     boundary so we don't accidentally match "Round 2" or year
 *     numbers (`2026`).
 */
const AMOUNT_REGEX =
  /\$\d{1,3}(?:,\d{3})*(?:\.\d{1,2})?|\b\d{1,3}(?:,\d{3})*\.\d{1,2}\b/g;

export function renderWithCoins(text: string | null | undefined): ReactNode {
  if (!text) return text ?? "";

  // Quick reject: no "$" and no decimal point means nothing to do.
  if (!text.includes("$") && !text.includes(".")) return text;

  // matchAll lets us interleave plain-text segments with matched
  // money values. Each match becomes an inline-flex span that
  // pairs the coin glyph with the bare digits (no "$" — the icon
  // replaces it).
  const out: ReactNode[] = [];
  let cursor = 0;
  let i = 0;
  for (const match of text.matchAll(AMOUNT_REGEX)) {
    const idx = match.index ?? 0;
    if (idx > cursor) {
      out.push(<Fragment key={`t-${i}`}>{text.slice(cursor, idx)}</Fragment>);
    }
    const raw = match[0];
    const amount = raw.startsWith("$") ? raw.slice(1) : raw;
    out.push(
      <span
        key={`m-${i}`}
        className="inline-flex items-baseline gap-0.5 tabular-nums"
      >
        <CoinIcon className="self-center" />
        {amount}
      </span>,
    );
    cursor = idx + raw.length;
    i++;
  }
  if (cursor < text.length) {
    out.push(<Fragment key={`t-end`}>{text.slice(cursor)}</Fragment>);
  }
  return out.length === 1 && typeof out[0] === "string" ? out[0] : out;
}
